### ISSUE TITLE
Upgrading CSS 

### ISSUE THREAD

**Issue by squigglybob** [kieranmillar/extra-recommended-sets#20]
Hi @kieranmillar 

I've really been enjoying playing through your sets on this site with my family. We'd been looking for some crafted sets rather than just random ones and these ones do the trick

I've been using it on my phone and I've noticed a few CSS tweaks that could improve the experience.

If you'd be interested I'd be happy to make some pull requests with some possible changes.

Some places I'm thinking:
* Larger/responsive Button sizes on smaller screens
* Larger/responsive select box sizes on smaller screen
* Larger/responsive tab sizes on smaller screens 

Let me know what you think, and I could have a look at it on saturday 😊

Thanks

**Comment by kieranmillar** [comment]
Go for it! Happy to receive PRs for styling improvements, the site right now is basically mostly default styling. This is partially because it's clean, but also partially because I'm lazy when it comes to styling.

I don't accept PRs for new kingdoms made by other people, and want to avoid importing dependencies and keep things close to native html/css/javascript to keep things easy and simple, but am otherwise open to all kinds of improvements.

**Comment by squigglybob** [comment]
Sweeeet!! 🍬 

I was thinking for the above just some basic responsive improvements, but some colours and fonts would be nice too.
I'm not a designer, but can CSS things to look nice.
So if there were some colours/styles of buttons that you like, I can riff off some screenshots.
Otherwise I'll just go for an updated basic style in pure CSS.

**Comment by squigglybob** [comment]
Ok, this is my todo list which I'll start working on for this PR

- [ ] increase text size on smaller screens (this may help with buttons and check boxes on smaller screens)
- [ ] centralise and max width content (will help for readability of wide text on larger screens)
- [ ] style the buttons to look similar to the tabs
- [ ] add a copy svg to copy buttons
