### ISSUE TITLE
Some other thoughts

### ISSUE THREAD

**Issue by squigglybob** [kieranmillar/extra-recommended-sets#22]
Hi @kieranmillar,

It was fun working with your code on the weekend. It's nicely laid out and I like the value of keeping it simple.

Here are some of my other thoughts, which you can discard or take or mold as you please 😊.  Also I'm thinking some of them may possibly be a companion app for keeping track of games/kingdoms played. It's up to you if you would like me to have a go at any of them.

## small ugrades
1. a clear button next to the 'get recommended sets' to clear the selected checkboxes
2. I added a max-width to the body which feels a bit hacky. There should probably be some container classes with max-width around pages instead. This would also enable things like the kingdoms to have full screen width colour on small screens, so that the grey background isn't right next to the text and button
3. when I'm trying to get out the cards for one of your sets and i'm scanning from phone to box to phone, i sometimes start taking the cards out for a different set by mistake.
Maybe there could be a way to highlight a set in a coloured background (maybe duration orange) to make it easier to track the set to be focussed on. I imagine this would work like a radio select, so you couldn't select multiple ones at a time, and could deselect it also.
4. When playing a set for a second time, it is easier to read the card names when the set is unchecked and then rechecked. Would it be possible to not cross out the text, and rely on the grey background and  tick to designate played status. The tick could even be upgraded to be more prominant and green or something. (Not sure how this would intersect with selecting in the point above)

## maybe bigger upgrades
These are maybe nice to haves and could stray into the realm of too much functionality beyond the scope of your site, and I imagine could also be a seperate app for logging plays and taking notes, but here are some thoughts I had for new features that could also enhance this site too.

a. A heart button/play again button: something to mark a set as one that the user would like to play again, or rated in a certain way. This could make it easier to find sets that you would like to play again.
b. A button to open a notes section so that a user can make some notes about their experience or thoughts on that set for next time they come to play it
c. A plays count (this feels more like a play logging app) to keep track of how many times you have played it.

For these ones having looked at your code, to prevent the need for a refactor of the currently saved played kingdoms id list, I would imagine saving a seperate object of whatever other info was needed per kingdom, keyed with the kingdom id.

**Comment by kieranmillar** [comment]
Thanks for your thoughts.
1. A button to uncheck all the checkboxes seems good to me.
2. I'm fine with more container divs for styling instead of applying directly to body.
3. In the official rulebooks, the cards are grouped by expansion, starting with the expansion whose rulebook it is and separated with a bullet point when it goes to the other expansion. That doesn't really translate so easily here, where I went with release order, which is the order they are listed in the checkboxes. I try to avoid using colour to categorise things except as a last resort for colour-blindness concerns. I don't really have a good idea for this one. I could look to add a separator so if you start with the wrong expansion box at least you know where to start at the other side. Implementation would require some changes to the underlying data, in a non-trivial way I think. Not sure on the best approach here.
4. Honestly I never expected people to play each of these kingdoms more than once. 10 for each combination was a number I considered large enough, and if you run out, I fully expect people to just move to randomising sets. This is why it crosses things out so clearly, so people can more easily see that they're finished with that one. I've never had any feedback on how people use this site so don't know how common it is to play kingdoms multiple times. If multiple plays are common and something I want to support, then the better approach would instead be a plays counter of some kind, instead of a played checkbox you could increase or decrease the played counter, there could be a big number to the left if you've played it at least once and a light pale green background. The local storage would be changed from an array of played kingdom ids to an array of objects with the id and a play count, if it has more than 0 plays. We would need to convert data from the old format one time. I should have version controlled the data with a wrapper object with a version number on it.

a. A favourite button with a separate tab to look at your favourites is fine. I think kingdoms on this screen would need to additionally say what expansions are being used for that kingdom.
b. Eh, I guess. But this is easy enough to add if we are going to change the data to use objects.
c. I sort of addressed this on point 4.


Overall this site was originally designed just as a way for me to host my designed kingdoms. I'm fine with added functionality but also like how the site is mostly just lists of kingdoms and little other bells and whistles to complicate that. I'm cool with features 1 and 2, am not sure what the best solution is for 3, and am a little apprehensive on the others, at least for now. But not completely opposed to them either.

**Comment by squigglybob** [comment]
No worries, thanks for considering them 😊 

I think I didn't explain 3 very well. If you replace set with kingdom in point 3 it should make more sense.
So functionality would be, you tap on a kingdom, and the background turns orange or some other colour to designate selection, to make it easier to see which kingdom you are getting cards out for.  I always find when I get a couple of cards out, I look back at my phone, and start getting cards out for a different kingdom 😆 This also happens with the rules book kingdoms. It could just be a personal issue as well.

I'll make a couple of issues for points 1 and 2, am happy to help in any way if you decide to go for any of the others 😃

**Comment by squigglybob** [comment]
On point 4, we have been very much enjoying the sets you have made on your site. Some of them are so good, we have wanted to play them again. But I agree, user feedback is useful for making these decisions, and feedback of 1 is not necessarily indicative to change things. It's up to you :)

**Comment by kieranmillar** [comment]
> I think I didn't explain 3 very well. If you replace set with kingdom in point 3 it should make more sense. So functionality would be, you tap on a kingdom, and the background turns orange or some other colour to designate selection, to make it easier to see which kingdom you are getting cards out for. I always find when I get a couple of cards out, I look back at my phone, and start getting cards out for a different kingdom 😆 This also happens with the rules book kingdoms. It could just be a personal issue as well.

Ah, I see! I am fine with a way to make a kingdom stand out if you hover or click on it. A border or different background colour are fine options.

**Comment by squigglybob** [comment]
Hi @kieranmillar, I've done 1-3 (and 4 ish when selected)

I'm thinking I agree with you on the principle of streamlined functionality for your site, and points a-c feel a bit different.
I've been thinking of making a dominion logging site, where you could copy and paste/write by hand, the kingdom that was played, and it would save it locally similar to your site.
Within that the heart system, play count and notes would make more sense I think.
I'll let you know how it goes 😃 

Thanks for letting me contribute to your site, I hope it's been helpful.
Give me a shout if there is anything else I could help with.

**Comment by kieranmillar** [comment]
@squigglybob Thanks for your contributions!
